### ISSUE TITLE
Clarify community chat/discussion URL in README

### ISSUE THREAD

**Issue by mrdziuban** [oyvindberg/bleep#437]
Hi, thank you for all your work on bleep!

As I've been testing it out, I've come up with a handful of questions and noticed [the Gitter linked in the README](https://gitter.im/oyvindberg/bleep) hasn't had any activity in over a year.

Is Gitter still the recommended place to get support, or should the URL be updated to point elsewhere, like the [tooling channel of the Scala discord](https://discord.com/channels/632150470000902164/635669047588945930) or the [GitHub discussions page](https://github.com/oyvindberg/bleep/discussions)?

**Comment by oyvindberg** [comment]
No, it's completely dead unfortunately. I created that channel right at the end of gitter, but it's not working out.
the tooling channel on the scala discord is the best place for now, with a direct ping to me so I see it.

I've meant to create a place on discord since forever, I should absolutely get around to it soon

**Comment by oyvindberg** [comment]
if you have the bandwidth, can you update the readme to point there?

**Comment by mrdziuban** [comment]
> if you have the bandwidth, can you update the readme to point there?

Sure thing, just opened #438
